"use client";
import type { Metadata } from "next";
import "../styles/globals.scss";
import "normalize.css";
import { FavoritesProvider } from "../context/FavContext";
import { ClientLayout } from "./ClientLayout";

// export const metadata: Metadata = {
//   title: "Marvel Challenge",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FavoritesProvider>{children}</FavoritesProvider>
      </body>
    </html>
  );
}
